# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_add <- function(v) {
    .Call('_copykatRcpp_rcpp_add', PACKAGE = 'copykatRcpp', v)
}

apply_cpp_col <- function(x) {
    .Call('_copykatRcpp_apply_cpp_col', PACKAGE = 'copykatRcpp', x)
}

apply_cpp_row_der <- function(x) {
    .Call('_copykatRcpp_apply_cpp_row_der', PACKAGE = 'copykatRcpp', x)
}

rcpp_sum <- function(v) {
    .Call('_copykatRcpp_rcpp_sum', PACKAGE = 'copykatRcpp', v)
}

apply_cpp_col_norm <- function(x) {
    .Call('_copykatRcpp_apply_cpp_col_norm', PACKAGE = 'copykatRcpp', x)
}

cpp_med <- function(x) {
    .Call('_copykatRcpp_cpp_med', PACKAGE = 'copykatRcpp', x)
}

apply_cpp_row_basel <- function(x) {
    .Call('_copykatRcpp_apply_cpp_row_basel', PACKAGE = 'copykatRcpp', x)
}

apply_cpp_row_DR2 <- function(x) {
    .Call('_copykatRcpp_apply_cpp_row_DR2', PACKAGE = 'copykatRcpp', x)
}

apply_cpp_row_temp <- function(x) {
    .Call('_copykatRcpp_apply_cpp_row_temp', PACKAGE = 'copykatRcpp', x)
}

apply_cpp_row_cfh <- function(x) {
    .Call('_copykatRcpp_apply_cpp_row_cfh', PACKAGE = 'copykatRcpp', x)
}

apply_cpp_row_base <- function(x) {
    .Call('_copykatRcpp_apply_cpp_row_base', PACKAGE = 'copykatRcpp', x)
}

apply_cpp_col_tempa <- function(x) {
    .Call('_copykatRcpp_apply_cpp_col_tempa', PACKAGE = 'copykatRcpp', x)
}

apply_cpp_col_aj <- function(x) {
    .Call('_copykatRcpp_apply_cpp_col_aj', PACKAGE = 'copykatRcpp', x)
}

